### ISSUE TITLE
I want to know which version of your pytorch ,cuda and ME. 

### ISSUE THREAD

**Issue by BiaoBiaoLi** [XuyangBai/PointDSC#1]
Thanks your work!!!
I want to know which version of your pytorch ,cuda and ME. 
Because I have this error, with the old version of ME when i use the FCGF before:
Traceback (most recent call last):
  File "demo_registration.py", line 10, in <module>
    from misc.fcgf import ResUNetBN2C as FCGF
  File "/Bill/Project/PointDSC/misc/fcgf.py", line 77, in <module>
    region_type=ME.RegionType.HYPER_CUBE,
  File "/opt/conda/lib/python3.7/enum.py", line 349, in __getattr__
    raise AttributeError(name) from None
AttributeError: HYPER_CUBE

Thanks

**Comment by XuyangBai** [comment]
CUDA 10.1, PyTorch 1.6.0 and ME v5.0. I remember that from ME v4.0 -> v5.0 some layers change their name eg, HYPERCUBE -> HYPER_CUBE. You may upgrade your ME or change the layer name back to HYPERCUBE.

**Comment by BiaoBiaoLi** [comment]
OK, Thanks!!
I have the same version CUDA 10.1, PyTorch 1.6.0， but I cannot install the ME.
I see the requirement on https://github.com/NVIDIA/MinkowskiEngine, which tells us PyTorch 1.6.0 cannot support.
![image](https://user-images.githubusercontent.com/44672683/113434632-ead43f80-9413-11eb-8765-a719b0c9afec.png)
Thanks!!

**Comment by XuyangBai** [comment]
I didn't remember whether I meet problems when install ME v5.0 on my environment, you may try to use a previous version and modify the layer name accordingly if you really cannot install ME v5.0.

**Comment by BiaoBiaoLi** [comment]
Thanks!! I install it with pytorch1.8 and cuda11.

**Comment by XuyangBai** [comment]
Cool, Glad to hear you find the solution. Please open another issue if you have other questions.
