### ISSUE TITLE
question about the number of input points

### ISSUE THREAD

**Issue by dreamcubeblock** [XuyangBai/PointDSC#10]
the number of input points between train and test is different,and each one in the test set is different.If i scale it to 5000,will it effect the final result?

**Comment by XuyangBai** [comment]
Hi thanks for your interest in our work. The network is able to handle inputs of different size and we use 1000 points during training for a larger batch_size. During inference, my experience is more points you have, the better performance you will get (but with a larger memory and computation cost).

**Comment by dreamcubeblock** [comment]
So if we want to compair with your method on 3dmatch testset,we have to
