### ISSUE TITLE
What tools to plot the FIgure 6.

### ISSUE THREAD

**Issue by ninglixu** [XuyangBai/PointDSC#11]
Hi Xuyang,

What tool to plot the Figure 6 in your paper(feature similarity distribution of inlier and non-inlier pairs).  It is very descriptive and vivid.

Thanks.

**Comment by XuyangBai** [comment]
Hi, thank you for your interest. I use [violinplot](https://matplotlib.org/stable/gallery/statistics/customized_violin.html#sphx-glr-gallery-statistics-customized-violin-py) in `matplotlib` to plot the figure.

**Comment by ninglixu** [comment]
Thanks a lot!
