### ISSUE TITLE
question about config file in make_fragments.py

### ISSUE THREAD

**Issue by yaorz97** [XuyangBai/PointDSC#15]
Thank you for your excellent work!!! Can you provide your json file to generate fragments of augmented ICL-NUIM dataset?

**Comment by XuyangBai** [comment]
Hi, I follow the multiway registration pipeline of open3d and use the same config in [here](https://github.com/intel-isl/Open3D/tree/master/examples/python/reconstruction_system/config/redwood_simulated) so I do not upload them to this repo.

Best,
Xuyang
