### ISSUE TITLE
FileNotFoundError:[Error 2] No such file or directory: 'redwood_simulated/livingroom1-simulated.json'.

### ISSUE THREAD

**Issue by lian0809** [XuyangBai/PointDSC#3]
when I tring to Reproduce your paper PointDsc, I encounter a FileNotFoundError:[Error 2] No such file or directory: 'redwood_simulated/livingroom1-simulated.json'.
And I've already found all directorys ,but failed to find it.
so maybe you forgot upload it or other situation I don't konw 
hope your reply

**Comment by xiyue-wx** [comment]
I'd also met the question!

**Comment by XuyangBai** [comment]
Hi, I follow the multiway registration pipeline of open3d and use the same config in [here](https://github.com/intel-isl/Open3D/tree/master/examples/python/reconstruction_system/config/redwood_simulated) so I do not upload them to this repo. Sorry for the inconvenience.

Best,
Xuyang

**Comment by XuyangBai** [comment]
Feel free to re-open this issue if you have any further questions.

**Comment by Feegooddddd** [comment]
I also meet this problem

**Comment by Feegooddddd** [comment]
DaLao,could you just give me the file that I can not find it in open3d,thank you ,sorry for my stupid.

**Comment by hah123aha** [comment]
> DaLao,could you just give me the file that I can not find it in open3d,thank you ,sorry for my stupid.

I also meet this problem,can you help me?

**Comment by Fengyaoyao-lgl** [comment]
I also meet this problem,can you help me?thank you ,sorry for my stupid.
