### ISSUE TITLE
cal_fcgf process_kitti error

### ISSUE THREAD

**Issue by Gardlin** [XuyangBai/PointDSC#4]
when i run cal_fcgf of kitti dataset processing  ,  it  turns out to be an error  in  the  function    process_kitti ,            
```
                xyz0_t = apply_transform(xyz0[sel0], M)
                pcd0 = make_point_cloud(xyz0_t)
                pcd1 = make_point_cloud(xyz1[sel1])
```when i change the index to     apply_transform(xyz0[sel0[1]], M)  , it  goes well  but   error  become like this
`zlib.error: Error -3 while decompressing data: invalid distance code`

so   I  want to  know  is  it  exactly  correct  of   the  code:    xyz0_t = apply_transform(xyz0[sel0], M)

**Comment by XuyangBai** [comment]
Hi, sorry I can not understand your question. Could you explain a little bit?

**Comment by Gardlin** [comment]
when I  run cal_fcgf.py  to  process   kitti dataset, it turns out to be an error in the  below code
```
                xyz0_t = apply_transform(xyz0[sel0], M)
                pcd0 = make_point_cloud(xyz0_t)
                pcd1 = make_point_cloud(xyz1[sel1])
```
it   seems to  work well   when  i   change  the code    **apply_transform(xyz0[sel0], M)**  to  **apply_transform(xyz0[sel0[1]], M)**,but   some  other  errors occured

**Comment by XuyangBai** [comment]
Hi I guess that was due to the change of interface of MinkowskiEngine. You may change to ME 5.0 which is the same as mine, or you can debug by printing the shape of `xyz0` and `sel0`, they should be `[N, 3]` and `[4, 4]`

**Comment by Gardlin** [comment]
Thanks a lot, the  shape of  `xyz0 ` is  `[N,3]  `,but `sel0 ` is  not  a tensor, it's   a tuple  consists  of  two  tensors,in which the shape of  the first tensor  is  `[M ,3] `,the shape of  the  second  tensor  is  `[M, ]`
I  will  downgrade ME to 5.0 ,thanks  a lot

**Comment by Gardlin** [comment]
However ,  I  find  that  the  versionof ME  is   0.5.0,  so  how   can   I  change   the  `ME.utils.sparse_quantize`  function    or  reshape  the  `sel0`  to   make  it `  [4 ,4]  ` shape

**Comment by XuyangBai** [comment]
Sorry `[4,4]` is the shape of `M`.  You can see the document [here](https://nvidia.github.io/MinkowskiEngine/utils.html#sparse-quantize). What we need is the indices of quantized coordinates, you can figure out which tensor of the returned tuple is the indices. From your description, it should be the second one (I guess the shape of the second tensor is `[N, ]` so we can use it to indexing `xyz0` to get the voxel-downsampled point clouds).  I borrow the processing code of KITTI from [here](https://github.com/chrischoy/FCGF/blob/master/lib/data_loaders.py#L285), you can check their modification on the updating of ME.

I cannot reach my dev environment currently and maybe I use another version of ME. Sorry for the inconvenience.

**Comment by XuyangBai** [comment]
Please reopen the issue if you have further questions.
