### ISSUE TITLE
Can you share the model？

### ISSUE THREAD

**Issue by WJinhai** [XuyangBai/PointDSC#5]
weight_path='misc/ResUNetBN2C-feat32-3dmatch-v0.05.pth'  is not in the package ， can you share the model？

**Comment by XuyangBai** [comment]
Hi, you can download the model [here](http://node2.chrischoy.org/data/projects/DGR/ResUNetBN2C-feat32-3dmatch-v0.05.pth) from [DGR repo](https://github.com/chrischoy/DeepGlobalRegistration).
