### ISSUE TITLE
How to test on our own point cloud data using PointDSC?

### ISSUE THREAD

**Issue by Yellowshuohahaha** [XuyangBai/PointDSC#6]
Hi, thanks for sharing the code. I want to use PointDSC to registrate two point cloud with pcd format. Is there any tutorial？

**Comment by XuyangBai** [comment]
Hi, thanks for your interest. You can take a look at `demo_registration.py` which takes two point cloud with `ply` format and output the registration result. You can change the io function to read your pcd format data. And you can try to use FPFH descriptor first if you do not have MinkowskiEngine installed.

**Comment by Yellowshuohahaha** [comment]
Thank you very much! I will try it.
