### ISSUE TITLE
Extract FPFH feature on KITTI dataset

### ISSUE THREAD

**Issue by rann1018** [XuyangBai/PointDSC#7]
Hi,

Thanks for sharing valuable code.
However, in the cal_fpfh.py script, I do not find how to extract features on KITTI dataset?
Should I process the raw point cloud similar to other datasets with voxel_size=0.05?

Thanks a lot for your attention and look forward to your reply.

Best regards

**Comment by XuyangBai** [comment]
Hi @rann1018 Thanks for your interest in this work. It seems I forget to add the code for extracting FPFH on KITTI, but you could write your code using the functions in open3d following other datasets' implementation. For the voxel size, I use 0.30m. If you met some questions during implementation, I am glad to help.

Best,
Xuyang.

**Comment by rann1018** [comment]
Thanks a lot for your quick reply. It really helps.
